# Generated by Django 4.2.16 on 2024-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_tasks'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='categories.category'),
        ),
    ]
